url: upkeepcare.org
baseurl: ""

# Site settings
title: Upkeep Care
email: brobertsonagp@gmail.com
description: "Welcome to Upkeep Care!"

# Team names, titles and social links
people:
- name: Wendy Jiang
  pic: wendy.jpeg
  position: Head of Partnerships
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/wendy-jiang-514a62103/

- name: Kiley Pratt
  pic: kiley.png
  position: Head of Product
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kiley-pratt/

- name: Blake Robertson
  pic: blake.jpeg
  position: Head of Business
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/blake-robertson/

- name: Peter Yu
  pic: peter.jpeg
  position: Head of Technology
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/zongyang-peter-yu/

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: New Haven, 06520

# Build settings
markdown: kramdown
permalink: pretty
